spring.application.name=UniBridge

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/unibridge

# 아래 두개에 자신의 mysql 유저(root 등)와 비번을 등록하고 .gitignore에 추가해주세요
# mysql 사용자 모르면 카톡으로 문의해주세요

# if above two lines are showing ???
# IntelliJ settings -> Editor -> File Encodings -> Default properties file encoding -> UTF-8
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
